### ISSUE TITLE
Windows Defender found Virus Trojan:AndroidOS/MuItiverze

### ISSUE THREAD

**Issue by SeriousM** [cyberark/PipeViewer#1]
## Summary

*Provide brief overview and context for the discovered bug.*

## Steps to Reproduce

1. Download the Release
2. Open the Zip Package
3. Find Windows Defender issuing problems

![image](https://user-images.githubusercontent.com/462013/219039794-1ad074b9-5374-46d9-8d71-37995ccaa027.png)

Maybe add a warning to the readme or change the code?

**Comment by g3rzi** [comment]
Thanks, not sure why it happened.
I will look at that next month because I am OOO.
We will check if we can solve it or like your suggestion, add a note about that.

**Comment by cosad3s** [comment]
Also identified as "Wacatac.H!ml" 
![image](https://user-images.githubusercontent.com/2116674/226170264-0c5e086c-55b7-42a0-a3c6-424bab2d1cbb.png)

**Comment by g3rzi** [comment]
I added a warning:
https://github.com/cyberark/PipeViewer#warning

We can't change it because it depends on the NtObjectManager package which is flagged as a virus.
